### ISSUE TITLE
Implement a base for assets

### ISSUE THREAD

**Issue by xipasduarte** [log-oscon/generator-log-wp-plugin#2]
The assets folder should be present, even without a gulp (or any other builder) present.
Choose a folder name that aligns both Themes and Plugins.

**Suggestion:**
- Have the assets on a `/public` folder with a build relation as follows:

`src/scripts` => `public/`
`src/styles` => `public/`
`src/images` => `public/images`

- CSS and JS assets file names:

Frontend: `plugin-slug.css|js`
Backend: `plugin-slug-admin.css|js`

**Comment by Narayon** [comment]
This should not be the common behavior because some plugins don't have assets.  
A sub-generator is already on the roadmap, so I'm closing this issue.
