### ISSUE TITLE
Como lidar com assets estáticos?

### ISSUE THREAD

**Issue by csrui** [log-oscon/generator-log-wp-plugin#3]
Qual é a estrutura definida para assets tanto pré compilação como pós compilação.

Proposto está:

* src/scripts => public/
* src/styles => public/
* src/images => public/images

Exemplos:

* Frontend: plugin-slug.css|js
* Backend: plugin-slug-admin.css|js

**Comment by xipasduarte** [comment]
I've ported your suggestion to issue #2
