### ISSUE TITLE
Improve `lib/` resources and structure

### ISSUE THREAD

**Issue by xipasduarte** [log-oscon/generator-log-wp-plugin#8]
Make the `lib/` folder have all abstract classes usually used for CPT and Taxonomy registration, for example.

Also create the folder structure associated to most uses.

Note: everything should be there without questioning. The developer should delete what he doesn't need, rather then making a decision at the bootstraping stage.

**Comment by RicCastelhano** [comment]
I was thinking of having those as subgenerators (actually it's how the Taxonomy subgenerator was built)

**Comment by xipasduarte** [comment]
My point is mute in terms of the Taxonomy class, but for everything that still has no sub-generator you don't have the files there.

By default have everything, then start removing and making sub-generators. Otherwise, we will still be making things differently across several projects, which defeats the point of this.

**Comment by RicCastelhano** [comment]
Totally agree !!!
Will submit the CPT subgenerator shortly and then we should proceed with your suggestion.

**Comment by Narayon** [comment]
Added a [pull-request](#13) with CPT sub-generator.  
I think we should close this issue because I don't agree that we should add code to be deleted.  
A sensible developer should be able to extract all necessary structure by looking at the generated files, from the generator and sub-generators.  
What do you think?

**Comment by xipasduarte** [comment]
Being something that you use, this should reflect your current practices and standards. So I say you should do whatever you agree to be best.

**Comment by Narayon** [comment]
Although this repo is prefixed with the company name, the generator is open source.  
Everyone is more than welcome to use it and contribute to it, not only with code but also with opinions/suggestions. Everyone will appreciate a better generator.  
The standards used in here are generic enough to be helpful for almost every situation.  
We can disagree - it looks like we will! - but the discussion can be a plus to the generator and that's the point.  
That said, I'm closing the issue. The discussion is still open, though.

**Comment by xipasduarte** [comment]
I wasn't talking about the "you" as in "company", but the maintainers of the repository. I'm happy to give my feedback whenever you'd like :)

I still think that abstract classes should be there, at least until the mechanism to generate them is not implemented. Otherwise you still have to copy&paste things from other projects 😉

**Comment by Narayon** [comment]
The most common abstract classes are already implemented on sub-generators.  
Maybe the reason I don't agree with you relates to the way I code: I only create abstract classes when I see the need for them.  
I think that forcing them is an anti-pattern because reinforces the idea that inheritance should be your first tool to DRY, which is not necessarily true.

**Comment by xipasduarte** [comment]
@Narayon I'm not going to digress, you are mixing your "personal" style into something that had nothing to do with that. Honestly, this issue is solved because you said there are sub-generators for those common abstract classes and their use cases.

I advise you to put your comment on "anti-pattern" to use, if you really feel that way, because you are arguing against something that the sub-generator implemented, i.e., make a PR with your leaner suggestion 😉
